import {
    Check,
    ChevronLeft,
    Image,
    Loader2,
    Moon,
    SunMedium,
    Trash,
    User,
    PencilRuler,
    Menu,
    ScanEye,
    LayoutPanelLeft,
    PanelRightOpen,
    LucideProps,
    Settings,
    Braces,
    CircleUser,
    Target,
    ArrowUpRight,
    Mail,
    Linkedin,
    Grip,
    Search,
    BadgeHelp,
    ShoppingCart,
    Bookmark,
    ArrowRight,
    X,
    PackageOpen,
    LogOut
} from "lucide-react"

export const Icons = {
    homeLogo: Grip,
    editorLogo: PencilRuler,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    trash: Trash,
    page: File,
    media: Image,
    user: User,
    sun: SunMedium,
    moon: Moon,
    check: Check,
    menu: Menu,
    preview: ScanEye,
    panelRightOpen: PanelRightOpen,
    settings: Settings,
    json: Braces,
    profile: CircleUser,
    projects: Target,
    linkArrow: ArrowUpRight,
    mail: Mail,
    search: Search,
    help: BadgeHelp,
    cart: ShoppingCart,
    wishlist: Bookmark,
    arrowRight: ArrowRight,
    cross:X,
    orders: PackageOpen,
    logout: LogOut

}